menu.backButton = Назад

menu.mainMenu.playButton = Гамать
menu.mainMenu.loadButton = Грузнуть
menu.mainMenu.optionsButton = Сделать шоб норм было
menu.mainMenu.exitButton = Нахуй
menu.mainMenu.gameName = Крч игра

menu.loadMenu.loadButton = Грузнуть
menu.loadMenu.deleteButton = Похерить

menu.pauseMenu.toMainMenuButton = Главная менюшка
menu.pauseMenu.nameOfMenu = Пауза

menu.saveMenu.defaultSaveName = Без имени нах
menu.saveMenu.saveButton = Сохранить
menu.saveMenu.nameOfMenu = Сохранить